- name: Handlers play
  hosts: all
  ignore_errors: yes
  tasks:
  - name: copy index
    copy:
      src: /tmp/index2.html
      dest: /usr/share
    notify:
    - restart_web
  - name: Copy nothing
    copy:
      src: /tmp/nothing
      dest: /usr/share
  handlers:
  - name: restart_web
    service:
      name: apache2
      state: restarted
