- name: play
  hosts: all
  tasks:
  - name: include copy playbook
    include_tasks: tasks/copy.yaml
  - name: include install "{{ webserver }}" playbook
    include_tasks: tasks/install_webserver.yaml
